name: Build UWP App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore SampleCalc.sln

      #- name: Build UWP app
      #  run: msbuild SampleCalc.sln /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Never

      #- name: Create app package
      # run: msbuild YourUWPProject.csproj /t:Package /p:Configuration=Release

      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1.3
        
      - name: Build Test
        run: msbuild ${{github.workspace}}\SampleCalcTest\SampleCalcTest.csproj /t:Build /p:Configuration=Release /p:Platform=x64
          
      - name: Run Test
        run: vstest.console.exe /Logger:trx /Platform:x64 /framework:frameworkuap10 ${{github.workspace}}\SampleCalcTest\bin\x64\Release\SampleCalcTest.build.appxrecipe

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        with:
          files: ${{github.workspace}}\TestResults\*.trx
        
